/* DO NOT EDIT THIS FILE - it is machine generated */

#ifndef __org_thenesis_midpath_io_backend_cldc_RandomAccessFile__
#define __org_thenesis_midpath_io_backend_cldc_RandomAccessFile__

#include "jni.h"

#ifdef __cplusplus
extern "C"
{
#endif

extern jint Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_open (JNIEnv *env, jobject, jstring, jboolean);
extern void Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_closeInternal (JNIEnv *env, jobject, jint);
extern jlong Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_getFilePointerInternal (JNIEnv *env, jobject, jint);
extern jlong Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_lengthInternal (JNIEnv *env, jobject, jint);
extern void Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_seekInternal (JNIEnv *env, jobject, jint, jlong);
extern void Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_setLengthInternal (JNIEnv *env, jobject, jint, jlong);
extern jint Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_readInternal (JNIEnv *env, jobject, jint, jbyteArray, jint, jint);
extern jint Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_skipInternal (JNIEnv *env, jobject, jint, jint);
extern void Java_org_thenesis_midpath_io_backend_cldc_RandomAccessFile_writeInternal (JNIEnv *env, jobject, jint, jbyteArray, jint, jint);

#ifdef __cplusplus
}
#endif

#endif /* __org_thenesis_midpath_io_backend_cldc_RandomAccessFile__ */
