#!/bin/sh

SYSTEM_PROPERTIES="\
-Djavax.microedition.io.Connector.protocolpath=com.sun.midp.io \
-Dmicroedition.profiles=MIDP-2.0 \
-Dmicroedition.configuration=CLDC-1.1 \
-Dmicroedition.locale=en-US \
-Dmicroedition.platform=generic \
-Dmicroedition.encoding=ISO8859_1 \
-Dmicroedition.hostname=localhost \
-Dmicroedition.commports= \
-Dmicroedition.jtwi.version=1.0 \
-Dmicroedition.media.version=1.1 \
-Dsupports.mixing=true \
-Dsupports.audio.capture=false \
-Dsupports.video.capture=false \
-Dsupports.recording=false \
-Daudio.encodings="encoding=audio/wav encoding=audio/x-wav encoding=pcm encoding=audio/mp3 encoding=audio/ogg" \
-Dvideo.snapshot.encodings="encoding=png encoding=image/png" \
-Dvideo.encodings= \
-Dstreamable.contents="encoding=audio/wav encoding=audio/x-wav encoding=pcm encoding=audio/mp3 encoding=audio/ogg" \
-Dmicroedition.io.file.FileConnection.version=1.0 \
-DBluetooth.api.version=1.1 \
-Dobex.api.version=1.1 \
-Dbluetooth.l2cap.receiveMTU.max=1024 \
-Dbluetooth.master.switch=true \
-Dbluetooth.connected.devices.max=6 \
-Dbluetooth.sd.trans.max=8 \
-Dbluetooth.sd.attr.retrievable.max=16 \
-Dbluetooth.connected.inquiry=true \
-Dbluetooth.connected.inquiry.scan=true \
-Dbluetooth.connected.page=true \
-Dbluetooth.connected.page.scan=true \
-Dmicroedition.m3g.version=1.1 \
-Dmicroedition.location.version=1.1 \
-Dmicroedition.m2g.version=1.1 \
-Dmicroedition.m2g.svg.version=1.1 \
-Dmicroedition.m2g.svg.baseProfile=tiny \
-Dxml.jaxp.subset.version=1.0 \
-Dxml.rpc.subset.version=1.0 \
-Dwireless.messaging.version=2.0 \
-Dwireless.messaging.sms.smsc=+17815511212 \
-Dwireless.messaging.mms.mmsc=+17815511212 \
"

# -Dmicroedition.pim.version=
# -Dmicroedition.global.version=
# -Dmicroedition.sip.version=1.0.1 \
# 
# -Dcom.sun.midp.io.http.proxy=
# -Dcom.sun.midp.io.http.force_non_persistent=

