
CFLAGS = `pkg-config --cflags gtk+-2.0` -I/usr/include/classpath
LDFLAGS = `pkg-config --libs gtk+-2.0`

SOURCES=org_thenesis_microbackend_ui_gtk_GTKBackend.c standard/standard_input.c

include Makefile.all

