
CFLAGS = `pkg-config --cflags gtk+-2.0 hildon-libs` -I/usr/include/classpath
LDFLAGS = `pkg-config --libs gtk+-2.0 hildon-libs`

SOURCES=org_thenesis_microbackend_ui_gtk_GTKBackend.c maemo/maemo_input.c

include Makefile.all
